### ISSUE TITLE
unable to run developers environment

### ISSUE THREAD

**Issue by cassfiji** [yasushisakai/bikebump-web#13]
Possibly related to an included file /data/roads.json.

**Comment by yasushisakai** [comment]
added roads.json file in /data/
https://github.com/yasushisakai/bikebump/blob/master/data/roads.json

(this is still assigned to be ignored)

**Comment by cassfiji** [comment]
May also want to add a roads.json to the production branch so it works off of download.

**Comment by yasushisakai** [comment]
now roads.json is excluded from .gitignore (for both master and production branch), also a uploaded data folder [here](https://github.com/yasushisakai/bikebump/releases/download/v0.0.4/data.zip).
