### ISSUE TITLE
Integrate Offline/Online with Firebase

### ISSUE THREAD

**Issue by kifleW** [yasushisakai/bikebump-web#34]

**Comment by yasushisakai** [comment]
function calls you might need for implementation

- storeBlob
here you will find the [storeBlob](https://github.com/yasushisakai/bikebump-web/blob/master/app/helpers/storage.js) function, it returns a Promise.
use this function 'name' as a placeholder that simply uploads a single file

- handlefileUploading(bool)
function for changing the Redux states **soundclips.isUploading**

- handleAppendFilesToUpload(filename)
function for appending a single file to Redux states **soundclips.filesToUpload**

FYI, [Firebase lets you monitor the status of upload](https://firebase.google.com/docs/storage/web/upload-files)
(middle of this page)

note you don't need to integrate into the app yet.
